/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:c257a54c-be83-48f4-9cc4-faacef34fb4f",
    "aws_cognito_region": "eu-central-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "49551eeb7678478fbc2468e99b1ae479",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
